import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "next-themes";
import { cn } from "@/lib/utils";
import { ModalProvider } from "@/components/providers/modal-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <ClerkProvider>
        <body className={cn(inter.className,
          "bg-white dark:bg-[#213338]"
        )}>
      <ThemeProvider
      defaultTheme="dark"
      attribute="class"
      enableSystem={false}
      storageKey="discord-theme"
      >
        <ModalProvider />
        {children}
      </ThemeProvider>
        </body>
    </ClerkProvider>
    </html>
  );
}
